# Generated by Django 4.0.3 on 2022-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
